### ISSUE TITLE
std::time is unavailable on wasm32

### ISSUE THREAD

**Issue by Jinxit** [lucidfrontier45/localsearch#29]
I've been using localsearch for a while now, it's a great little library.

It just so happens to be that I'm running it in a WebWorker context using WebAssembly, where `std::time` is not supported. There's a few ways around this, either using something like [wasmtimer](https://crates.io/crates/wasmtimer), [web-time](https://crates.io/crates/web-time) or even just `cfg`ing out the time-based deadline completely as a feature toggle.

What do you think?

**Comment by lucidfrontier45** [comment]
Hi, thank you for raising this issue.
I created this [feature/web-time branch](https://github.com/lucidfrontier45/localsearch/tree/feature/web-time) which use `web-time` if target family is wasm. Can you try it?

**Comment by Jinxit** [comment]
Works perfectly, much appreciated!

**Comment by lucidfrontier45** [comment]
@Jinxit 

I published v0.12.1 to crates.io.
